Actor TargetIsAnExplosiveBarrel : Inventory
{
inventory.maxamount 1
}

Actor HasExplosiveBarrel : Inventory
{
inventory.maxamount 1
}

Actor GrabbedBarrel : Inventory
{
inventory.maxamount 1
}

Actor GrabbedBurningBarrel : Inventory
{
inventory.maxamount 1
}

Actor ComingTOGetTheBarrel : Inventory
{
inventory.maxamount 1
}

Actor BarrelExpMeasure : Inventory
{
inventory.maxamount 950
}

Actor BarrelExpMeas2 : Inventory
{
inventory.maxamount 950
}

Actor ExplosiveBarrelPartialRemains
{
-Solid

states
	{
	Spawn:
		BEXP RSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRSTRST 4 bright Light("BarrelDeadLight")
		BEXP U -1
		Stop
	}
}

Actor NewBarrelExploFX
{
	Radius 0
	Height 0
	RenderStyle Add
	Alpha 1
	Scale 1.45
	  +NOGRAVITY
	  +NOINTERACTION
	  +NOBLOCKMAP
	  +NOTELEPORT
	  +ForceXYBillboard
	  +CLIENTSIDEONLY
	States
	{
	Spawn:
		X005 ABCDEFGHIJKLMNOPQRSTUVWX 1 bright
		stop
	}
}

enum PBBarrelStatus
{
	PBB_Bloody=0,
	PBB_Frozen=0,
	PBB_MeleeDamaged=0, //0 normal, 1 punched once, 2 kicked or punched twice
	PBB_AxeCut=0, //0 normal, 1 cut but spewing, 2 finished spewing
	PBB_BulletHoles=0, //0 normal, 1 shell pellets, 2 large hole
};

class PB_Barrel : SwitchableDecoration Replaces ExplosiveBarrel
{
	default
	{
		damagefactor "Trample", 0.0;
		damagefactor "Kick", 0.1;
		damagefactor "LowKick", 0.1;
		damagefactor "Melee", 0.1;
		damagefactor "Extremepunches", 0.1;
		damagefactor "Fatality", 10.1;
		damagefactor "SuperPunch", 10.1;
		damagefactor "ExplosiveImpact", 0.4;
		damagefactor "Fire", 3.5;
		damagefactor "GibRemoving", 0.0;
		damagefactor "BHFTOnBarrel", 500.0;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "Shrapnel", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "TeleportRemover", 0.0;
		//Species "Marines"
		Health 50;
		Radius 11;
		Height 32;
		Mass 200;
		DamageType ExplosiveImpact;
		MONSTER;
		-COUNTKILL;
		+NOBLOOD;
		-FRIENDLY;
		+NOICEDEATH;
		+PUSHABLE;
		+SLIDESONWALLS;
		+WINDTHRUST;
		+TELESTOMP;
		+NOBLOCKMONST;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		+EXTREMEDEATH;
		-DONTHURTSPECIES;
		+DOHARMSPECIES;
		+usespecial;
		+lookallaround;
		+ACTIVATEMCROSS;
		Activation THINGSPEC_Activate | THINGSPEC_ThingTargets | THINGSPEC_NoDeathSpecial;
		Speed 0;
		MaxTargetRange 1024
		DamageFactor "BHFT", 10.0;
		Painchance "Blood", 255;
		PainChance "Kick", 255;
		PainChance "SuperKick", 255;
		PainChance "SuperPunch", 255;
		PainChance "ExtremePunches", 255;
		DeathSound "excavator/explode";
		PainSound "barrel/pain";
		Obituary "$OB_BARREL";
		PainChance "DontCallTheBaron", 255;
		Painchance 255;
	}
	States
	{
	Spawn:
		TNT1 A 0 A_GiveInventory("TargetIsANExplosiveBarrel", 1);
	spawnloop:
		TNT1 A 0 A_Look;
	    EXB1 ABCDEF 1 A_JumpIfInventory("RedBloodSplatterz", 1, "Pain.Blood");
		loop;
	See:
		EXB1 ABCDEF 1
		{
			A_SpawnParticle("LightGreen", SPF_FULLBRIGHT, 70, 0.5, 0, (random(5,-5),random(5,-5)), 30, (random(1,10),random(1,10),random(1,10)), 0, 1.0, 0.05, random(-1,1));
			A_SpawnParticle("LightGreen", SPF_FULLBRIGHT, 70, 0.5, 0, (random(5,-5),random(5,-5)), 30, (random(1,10),random(1,10),random(1,10)), 0, 1.0, 0.05, random(-1,1));
			A_SpawnParticle("LightGreen", SPF_FULLBRIGHT, 70, 0.5, 0, (random(5,-5),random(5,-5)), 30, (random(1,10),random(1,10),random(1,10)), 0, 1.0, 0.05, random(-1,1));
			A_JumpIfInventory("RedBloodSplatterz", 1, "Pain.Blood");
		}
		TNT1 A 0 A_ClearTarget;
		Loop;

	Missile:
		TNT1 A 0;
		Goto See;
	
	Pain:
		EXB1 ABCDEF 1;
		TNT1 A 0 A_ClearTarget;
		Goto Spawn;
	
	Pain.Shotgun:
		EXB1 ABCDEF 1;
		TNT1 A 0
		{
			PBB_BulletHoles = 1;
		}
		TNT1 A 0 A_ClearTarget;
		Goto Spawn;
	
	Pain.Blood:
	    TNT1 A 0;
	    TNT1 A 0 A_GiveInventory("GotBloody", 1);
	    Goto StayBloody;
	StayBloody:
	    BARB ABCDEFGHIJKLM 2;
		Loop;
		
    Pain.Kick:
	Pain.SuperKick:
	Pain.ExtremePunches:
	Pain.SuperPunch:
		TNT1 A 0 A_JumpIfInventory("GotBloody", 1, "BloodyThrust1");
	    TNT1 A 0 A_Changeflag("FRIENDLY", 0);
	    BAR1 A 1 A_Pain;
		BAR1 A 0 A_Chase("","");
		TNT1 A 0 ThrustThingZ(0,8,0,1);
        BAR1 A 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 10, 0, 0);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		TNT1 A 0 A_Changeflag("FRIENDLY", 1);
        Goto See;
		
	BloodyThrust1:
	    TNT1 A 0 A_Changeflag("FRIENDLY", 0);
	    BARB A 1 A_Pain;
		BAR1 A 0 A_Chase("","");
		TNT1 A 0 ThrustThingZ(0,8,0,1);
        BARB B 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 10, 0, 0);
		TNT1 A 0 ThrustThingZ(0,8,0,1);
		TNT1 A 0 A_Changeflag("FRIENDLY", 1);
        Goto StayBloody;
		
	Pain.Melee:
		TNT1 A 0 A_JumpIfInventory("GotBloody", 1, "BloodyThrust2");
	    TNT1 A 0 A_Changeflag("FRIENDLY", 0);
	    BAR1 A 1 A_Pain;
		BAR1 A 0 A_Chase("","");
        BAR1 A 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
		TNT1 A 0 ThrustThingZ(0,10,0,1);
		TNT1 A 0 A_Changeflag("FRIENDLY", 1);
        Goto See
		
	BloodyThrust2:
	    TNT1 A 0 A_Changeflag("FRIENDLY", 0);
	    BARB A 1 A_Pain;
		BAR1 A 0 A_Chase("","");
        BARB B 1 A_FaceTarget;
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
		TNT1 A 0 ThrustThingZ(0,10,0,1);
		TNT1 A 0 A_Changeflag("FRIENDLY", 1);
        Goto See;
		
			
	Death:	
        BAR1 A 0;
        BEXP AB 2 BRIGHT;
		BEXP C 3 BRIGHT;
		TNT1 A 0 
		{
			A_Stop;
			A_SpawnItemEx ("BarrelExplosion",0,0,30,0,0,0,0,SXF_NOCHECKPOSITION,0);
		}
		BEXP D 1 BRIGHT;
		TNT1 AAAA 0 A_CustomMissile ("Shrapnel", 64, 0, random (0, 360), 2, random (30, 60)); //replace with hurtful shrapnel actor things
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_CustomMissile ("ShrapnelParticle", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0
		{
			A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			A_SpawnItem("WhiteShockwaveBig");
			A_SpawnItemEx ("NewBarrelExploFX", 0, 0, 20);
			A_SpawnItemEx ("BarrelKaboom",0,0,15,0,0,0,0,SXF_NOCHECKPOSITION,0);
			A_NoBlocking;
			A_Fall;
		}
		
		TNT1 AAAA 0 A_CustomMissile ("FireworkSFXType2", 64, 0, random (0, 360), 2, random (30, 60));
		TNT1 AA 0 A_CustomMissile ("HighExplosiveFlames", random (10, 20), 0, random (0, 360), 2, random (10, 90));
		EXPL AA 0 A_CustomMissile ("BigBlackSmokeLarger", 20, 0, random (0, 360), 2, random (10, 90));
        TNT1 AAA 0 A_CustomMissile ("PBExplosionparticles3", 64, 0, random (0, 360), 2, random (40, 90));
		TNT1 AAA 0 A_CustomMissile ("PBExplosionparticles4", 64, 0, random (0, 360), 2, random (40, 90));
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream;
        
		TNT1 A 0
		{
			A_CustomMissile("BarrelShrapnel1", 25, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("BarrelShrapnel2", 15, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("BarrelShrapnel3", 5, 0, random (0, 360), 2, random (0, 160));
			A_CustomMissile("BarrelShrapnel4", 5, 0, random (0, 360), 2, random (0, 160));
			A_PlaySound("FAREXPL", 3);
		}
		TNT1 AAAAAA 0
		{
			A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15))
			A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35))
			A_SpawnItemEx("TinyBurningPiece3", random (-45, 45), random (-45, 35))
		}
		TNT1 A 0 A_Jump(64, 2);
		TNT1 A 0 A_SpawnItem ("ExplosiveBarrelPartialRemains", 0);
		BEXP E 1;
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
		
		TNT1 AAA 8 A_CustomMissile("ExplosionSmoke", 1, 0, random (0, 360), 2, random (50, 130));

		BEXP Z 300 BRIGHT A_BarrelDestroy;
		BEXP Z 5 A_Respawn;
		Stop;
			
	Active:
        BAR1 B 1 A_FaceTarget;
		TNT1 A 0 A_JumpIfInTargetInventory("HasBarrel",1, "See");
		TNT1 A 0 A_JumpIfInTargetInventory("HasBurningBarrel",1, "See");
		TNT1 A 0 A_JumpIfInTargetInventory("PowerStrength",1, "GiveBarrel");
		Goto See;
		
	Death.Fatality:
        TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("GoSpecial", 1);
        TNT1 A 0 A_GiveToTarget("HasBarrel", 1);
        Stop;
		
	GiveBarrel:
        TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_ChangeFlag("SHOOTABLE", 1);
		BAR1 A 1 A_FaceTarget;
		TNT1 A 0 A_GiveToTarget("BarrelThrower", 1);
		TNT1 A 0 A_GiveToTarget("GrabbedBarrel", 1);
		TNT1 A 0 A_GiveToTarget("HasBarrel", 1);
        BAR1 ABCD 2;
		TNT1 A 0 A_PlaySound("barrel/pain");
        Stop;
		
	Death.Massacre:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("ExplosiveBarrel1");
		Stop;
	
	Death.BHFT:
	Death.BHFTOnBarrel:
		TNT1 A 0;
		TNT1 A 0 A_GiveToTarget("HasExplosiveBarrel", 1);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FAll;
		TNT1 A 1;
		Stop;
	
	Death.Kick:
	Death.ExtremePunches:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_ChangeFlag("THRUACTORS", 1);
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx ("ExplosiveBarrel",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION);
		TNT1 A 1;
		Stop;
	}
}

class BarrelShrapnel1
{
	default
	{
		Radius 2;
		Height 2;
		Speed 8;
		Mass 1;
		+NOBLOCKMAP
		+MISSILE
		+NOTELEPORT
		+MOVEWITHSECTOR
		//+CLIENTSIDEONLY
		+THRUACTORS
		+FLOORCLIP
		+DOOMBOUNCE
		+NOGRAVITY
		BounceFactor 0.5;
		Gravity 0.9;
		Mass 1;
    }
	States
    {
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			BRPT ABCDEFGH 1;
			TNT1 A 0 A_ChangeFlag("NOGRAVITY", 0);
			Goto Spawn2;
		Spawn2:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			BRPT ABCDEFGH 2;
			Loop;
		Death:
			TNT1 A 0;
			BRPT I 300;
			BRPT IIIIIIIII 2 A_FadeOut(0.1);
			Stop;
		Underwater:
		Splash:
			Goto Death;
    }
}


class BarrelShrapnel2: BarrelShrapnel1
{
	default
	{
		Scale 0.7;
	}
}

class BarrelShrapnel3: BarrelShrapnel1
{
	default
	{
		Scale 0.4;
	}
}

class BarrelShrapnel4: BarrelShrapnel1
{
	default
	{
		Scale 0.2;
	}
}

class BarrelKaboom: DeadMarine
{
	default
	{
		Game Doom;
	}
	States
	{
		Spawn:
		TNT1 A 1;
		TNT1 AAAA 0 A_CustomMissile ("SmallExplosionSpawner", 20, 0, random (0, 360), 2, random (0, 180));
		Stop;
	}
}